sudo: required
language: ruby
cache: bundler

rvm:
  # - 1.8.7
  # - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2

services: postgresql

env:
  - PGVERSION=9.1
  - PGVERSION=9.2
  - PGVERSION=9.3
  - PGVERSION=9.4

before_install:
  - psql --version
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql restart
  - psql --version

before_script:
  - psql -c 'create database pg_asset_reader_test;' -U postgres
