sudo: false
language: ruby
cache: bundler

rvm:
  # - 1.8.7
  # - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2

services: postgresql

before_script:
  - psql -c 'create database pg_asset_reader_test;' -U postgres
